services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - /home/lmarchi/Documentos/postgres:/var/lib/postgresql/data